#
# Module manifest for module 'ErrorRemover'
#
# Generated by: Karl Oswald
#
# Generated on: 5/19/2020
#

@{
    RootModule = './ErrorRemover.psm1'
    ModuleVersion = '0.0.1'
    GUID = '277fcac0-7d5b-4c82-ac24-ff72378d2e51'
    Author = 'Karl Oswald'
    CompanyName = 'None'
    Copyright = '(c) Karl Oswald. All rights reserved.'
    Description = ''
    PowerShellVersion = '5.0.0' # Minimum
    # RequiredModules = @( '../ErrorTypes/ErrorTypes.psm1' )
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @() # (.ps1xml) 
    # FormatsToProcess = @() # (.ps1xml)
    # NestedModules = @()
    FunctionsToExport = @()
    CmdletsToExport = @()
    VariablesToExport = '*'
    AliasesToExport = @()
    FileList = @(
        './ErrorRemover.psm1'
    )
}

